In [2]:
import pandas as pd
from sqlalchemy import create_engine, text

In [ ]:
url = "mysql+pymysql://avnadmin:"PASSWORD"@mysql-37f12a2a-pascalchidera21-0ad9.i.aivencloud.com:14160/defaultdb"
mysql_engine = create_engine( url, 
                              connect_args = {"ssl":{"ssl_mode":"REQUIRED"}},
                              pool_pre_ping = True
                            )

In [6]:
query1 = text("""SELECT 
                      * 
                 FROM 
                      Warehouse_Data.warehouse"""
             )
query2 = text("""SELECT 
                      * 
                 FROM 
                      Warehouse_Data.warehouse_orders"""
             )

with mysql_engine.connect() as conn:
    df1 = pd.read_sql(query1, con = conn)

with mysql_engine.connect() as conn:
    df2 = pd.read_sql(query2, con = conn)

In [8]:
df1.head()

,warehouse_id,warehouse_alias,maximum_capacity,employee_total,state
0,1543,Somerset Fulfillment Center,210,14,KY
1,2270,Bowling Green Warehouse,280,13,KY
2,2666,Lansing Fulfillment Center,290,16,MI
3,3417,Gatlinburg Warehouse,620,6,TN
4,3961,Lansing Storage Warehouse,740,22,MI

In [7]:
df2.head()

   order_id  customer_id  warehouse_id  order_date shipper_date
0       789         3731          8118  01/01/2019   01/04/2019
1       790         3486          8118    1/1/2019     1/4/2019
2       791         2623          8118    1/1/2019     1/4/2019
3       792         9869          8118    1/1/2019     1/4/2019
4       793         6866          8118    1/1/2019     1/4/2019

In [10]:
df1.describe()

       warehouse_id  maximum_capacity  employee_total
count     10.000000         10.000000       10.000000
mean    5173.300000        452.500000       14.400000
std     2991.814687        242.879142        5.680376
min     1543.000000        210.000000        5.000000
25%     2853.750000        246.250000       13.000000
50%     4149.500000        345.000000       15.000000
75%     7715.750000        710.000000       16.750000
max     9831.000000        780.000000       22.000000

In [11]:
df2.describe()

           order_id  customer_id  warehouse_id
count   9999.000000  9999.000000   9999.000000
mean    5788.000000  5470.125813   5556.591559
std     2886.607005  2601.663953   2532.789050
min      789.000000  1001.000000   1543.000000
25%     3288.500000  3206.000000   2666.000000
50%     5788.000000  5455.000000   6509.000000
75%     8287.500000  7709.500000   8118.000000
max    10787.000000  9999.000000   9080.000000

In [13]:
df1.dtypes

warehouse_id        int64
warehouse_alias       str
maximum_capacity    int64
employee_total      int64
state                 str
dtype: object

In [15]:
df1.isna().sum()

warehouse_id        0
warehouse_alias     0
maximum_capacity    0
employee_total      0
state               0
dtype: int64